kind: pipeline
name: default

steps:
- name: build
  image: python:3.7.0
  commands:
  - pip3 install -r requirements.txt
  - python3 ./www/app.py
services:
- name: database
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: pass
  command: [ "--character-set-server=utf8mb4" ]
  



